version: '3.9'
services:
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
    container_name: rtmp_server
  auth:
    build: ./auth
    ports:
      - "8000:8000"
    container_name: auth_server
    environment:
      - STREAM_KEY=supersecret